version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
    environment:
      - REDIS_HOST_PASSWORD=123qaz
      - PHP_MEMORY_LIMIT=-1
      - PHP_UPLOAD_LIMIT=16G

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_ENABLED=false
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 88:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html

  redis:
     image: redis
     restart: always
     command: redis-server --requirepass 123qaz

  db:
     image: postgres:alpine
     hostname: postgres_db
     restart: always
     volumes:
      - mysql_data:/var/lib/postgresql/data
     environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123qaz
     
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
